name: Deploy homepage on tag push

on:
  push:
    tags:
      - 'v*'  # vë¡œ ì‹œìž‘í•˜ëŠ” íƒœê·¸ê°€ í‘¸ì‹œë  ë•Œ ì‹¤í–‰ë¨ (ì˜ˆ: v1.0.0)
  workflow_dispatch:  # ðŸ‘ˆ ìˆ˜ë™ ì‹¤í–‰ ë²„íŠ¼ ì¶”ê°€
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract tag version
        id: extract_tag
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t homepage-namoo:${{ steps.extract_tag.outputs.TAG }} .

      - name: Tag image as latest
        run: docker tag homepage-namoo:${{ steps.extract_tag.outputs.TAG }} homepage-namoo:latest

      - name: Push Docker images (version + latest)
        run: |
          docker push homepage-namoo:${{ steps.extract_tag.outputs.TAG }}
          docker push homepage-namoo:latest

      - name: SSH & Deploy on Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 32111
          script: |
            docker pull homepage-namoo:latest
            docker-compose -f /home/homepage/www.namooinc.com/docker-compose.yml up -d
