name: Deploy homepage on tag push

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract tag version
        id: extract_tag
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Create .env file for Docker build
        run: |
          echo "NEXT_PUBLIC_KAKAO_MAP_KEY=${{ secrets.KAKAO_MAP_KEY }}" >> .env
          echo "ADMIN_ID=${{ secrets.ADMIN_ID }}" >> .env
          echo "ADMIN_PW=${{ secrets.ADMIN_PW }}" >> .env

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image (with .env)
        run: |
          docker build -t ghcr.io/rhistle-official/homepage-namoo:${{ steps.extract_tag.outputs.TAG }} .

      - name: Tag image as latest
        run: docker tag ghcr.io/rhistle-official/homepage-namoo:${{ steps.extract_tag.outputs.TAG }} ghcr.io/rhistle-official/homepage-namoo:latest

      - name: Push Docker images
        run: |
          docker push ghcr.io/rhistle-official/homepage-namoo:${{ steps.extract_tag.outputs.TAG }}
          docker push ghcr.io/rhistle-official/homepage-namoo:latest

      - name: SSH & Deploy on Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 32111
          script: |
            echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u rhistle-official --password-stdin
            docker-compose -f /home/homepage/www.namooinc.com/docker-compose.yml up -d --remove-orphans
