name: Deploy homepage on tag push

on:
  push:
    tags:
      - 'v*'  # v로 시작하는 태그가 푸시될 때만 실행됨

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract tag version
        id: extract_tag
        run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t homepage-namoo:${{ steps.extract_tag.outputs.TAG }} .

      - name: Push Docker image
        run: docker push homepage-namoo:${{ steps.extract_tag.outputs.TAG }}

      - name: SSH & Deploy on Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 32111
          script: |
            docker pull homepage-namoo:${{ steps.extract_tag.outputs.TAG }}
            docker tag homepage-namoo:${{ steps.extract_tag.outputs.TAG }} homepage-namoo:latest
            docker-compose -f /home/ubuntu/docker-compose.yml up -d
